'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const D=require('../sheet175/dispatch175'),R=require('../sheet173/registry173');
const hash=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
const zero='0'.repeat(64);
function syncDir(dir){const f=fs.openSync(dir,'r');try{fs.fsyncSync(f)}finally{fs.closeSync(f)}}
function append(file,obj){const f=fs.openSync(file,'a',0o600);try{fs.writeSync(f,JSON.stringify(obj)+'\n');fs.fsyncSync(f)}finally{fs.closeSync(f)}syncDir(path.dirname(file))}
function scan(file){let head=zero,seq=0,commits=[],pending=null;const used=new Set();if(!fs.existsSync(file))return{head,seq,commits,pending,used};const src=fs.readFileSync(file,'utf8');if(src&&!src.endsWith('\n'))throw Error('TORN_WAL');for(const l of src.split('\n').filter(Boolean)){let r;try{r=JSON.parse(l)}catch{throw Error('CORRUPT_WAL')}if(r.seq!==seq+1||r.prev!==head||r.hash!==hash({seq:r.seq,prev:r.prev,kind:r.kind,payload:r.payload}))throw Error('WAL_FORK');head=r.hash;seq=r.seq;if(r.kind==='prepare'){if(pending||used.has(r.payload.nonce))throw Error('PREPARE_FORK');pending=r.payload;used.add(pending.nonce)}else if(r.kind==='commit'){if(!pending||r.payload.prepareHash!==pending.prepareHash||r.payload.nonce!==pending.nonce)throw Error('COMMIT_FORK');commits.push(pending);pending=null}else throw Error('WAL_KIND')}return{head,seq,commits,pending,used}}
function open(file,issuerKey){file=path.resolve(file);fs.mkdirSync(path.dirname(file),{recursive:true});let state=scan(file);const lock=file+'.lock';function invoke(req,{fault}={}){let held=false;try{fs.mkdirSync(lock);held=true;syncDir(path.dirname(lock));const disk=scan(file);if(disk.head!==state.head)throw Error('STALE_WRITER');if(disk.pending)throw Error('PENDING_RECONCILIATION');const route=R.route(req.daughter,req.cortex);if(!route.capabilities.includes(req.op))throw Error('ROUTE_DENIED');const claims=D.authorize(req.permit,issuerKey,route,req.op);if(disk.used.has(claims.nonce))throw Error('REPLAY');const result=D.evaluate(req.op,req.input);if(result.valid===false)throw Error('INVALID_EVIDENCE');const p={nonce:claims.nonce,route:claims.route,op:req.op,inputHash:hash(req.input),resultHash:hash(result)};p.prepareHash=hash(p);const prep={seq:disk.seq+1,prev:disk.head,kind:'prepare',payload:p};prep.hash=hash(prep);append(file,prep);if(fault==='after-prepare')throw Error('INJECTED_AFTER_PREPARE');const commit={seq:prep.seq+1,prev:prep.hash,kind:'commit',payload:{nonce:p.nonce,prepareHash:p.prepareHash}};commit.hash=hash(commit);append(file,commit);state=scan(file);return{result,seq:state.seq,commits:state.commits.length,head:state.head}}finally{if(held){fs.rmdirSync(lock);syncDir(path.dirname(lock))}}}function recover(){const s=scan(file);if(s.pending)throw Error('PENDING_RECONCILIATION');state=s;return{commits:state.commits.length,head:state.head}}return{invoke,recover,status:()=>({commits:state.commits.length,pending:!!state.pending,head:state.head}),scan:()=>scan(file)}}module.exports={open,scan};
