from pathlib import Path
import json
p=Path(__file__).parent
r=json.loads((p/'gate166-results.json').read_text())
scenarios=[
('Nominal recovery','candidate',1.14,'Stable signed source quorum; no switching required',True,'VERIFIED'),
('Slow candidate','baseline',.70,'Three weak windows and minimum dwell; externally signed downgrade',True,'SIGNED DOWNGRADE'),
('Transient slowdown','candidate',.78,'Only one poor window; hysteresis rejects premature switch',True,'HYSTERESIS HOLD'),
('Drift detected','candidate',.61,'Fast EMA diverges from slow EMA; alert without cryptographic bypass',True,'DRIFT FLAG'),
('Signer unavailable','candidate',.60,'No external authorization: close path and fail closed',False,'FAIL CLOSED'),
('Replay old pin','baseline',1.23,'Stale signed generation rejected after independent floor advances',False,'ROLLBACK REJECT'),
('Crash between fsyncs','candidate',.68,'External floor ahead of local head; reviewed reconciliation required',False,'QUARANTINE'),
('Holdout re-promotion','candidate',1.25,'Four strong windows, cooldown expired and verified holdout approved',True,'SIGNED PROMOTION')]
js=json.dumps([dict(name=x[0],mode=x[1],ratio=x[2],detail=x[3],ok=x[4],status=x[5]) for x in scenarios])
html=r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>OASIS · SHEET 166 · Hysteresis & Witnessed Policy</title>
<style>
:root{color-scheme:dark;--background:#040b08;--panel:#0b1a13;--line:#24432f;--text:#e5ffeb;--muted:#8cab9b;--green:#59f19b;--amber:#ffd487;--red:#f2a9ab}*{box-sizing:border-box}body{margin:0;background:radial-gradient(ellipse at 80% 0,#112f1b 0,transparent 46%),var(--background);font:14px/1.55 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;color:var(--text)}main{max-width:1240px;margin:auto;padding:30px 20px 65px}header{display:flex;gap:24px;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line);padding-bottom:21px}.eyebrow{color:var(--green);font-size:11px;letter-spacing:.17em;font-weight:700}h1{font-size:clamp(24px,4vw,43px);letter-spacing:-.055em;margin:6px 0;line-height:1.1}h2{font-size:15px;margin:0 0 12px}small,.sub{color:var(--muted)}.status{padding:9px 12px;border:1px solid #356f4e;border-radius:7px;background:#0c301b;color:#9bffc3;font-weight:700;white-space:nowrap}section{margin-top:20px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.stat,.panel{border:1px solid var(--line);border-radius:10px;background:linear-gradient(155deg,rgba(22,50,31,.78),var(--panel));padding:19px}.stat strong{display:block;font-size:clamp(20px,3vw,30px);line-height:1.2;color:var(--green)}.stat span{color:var(--muted);font-size:11px}.two{display:grid;grid-template-columns:2fr 1fr;gap:16px}.buttons{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}button{border:1px solid #355942;color:#c8ead2;background:#102719;border-radius:7px;text-align:left;padding:11px 12px;font:inherit;cursor:pointer;transition:.12s}button:hover,button.active{border-color:var(--green);background:#173c25;color:#fff}button:focus-visible{outline:2px solid var(--green);outline-offset:2px}button small{display:block;font-size:10px}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.actions button{background:#193b29;color:#aafcbe}.terminal{background:#030907;border:1px solid #1c3525;border-radius:8px;padding:16px;font-size:12px;white-space:pre-wrap;min-height:94px;color:#c9f3d5}.meter{height:9px;border-radius:5px;background:#12261b;overflow:hidden;border:1px solid #244532;margin:9px 0 17px}.fill{height:100%;width:0;background:linear-gradient(90deg,#328d5c,#5bf5a4);transition:.2s}.pill{display:inline-block;border:1px solid #4c8b61;color:#79edab;border-radius:100px;font-size:11px;padding:4px 10px;margin-bottom:10px}.pill.blocked{border-color:#a05b5b;color:var(--red)}svg{width:100%;height:auto}svg text{font-family:inherit}#scenario-description{min-height:44px}.legend{display:flex;gap:19px;flex-wrap:wrap;color:var(--muted);font-size:11px}.dot{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:6px}footer{color:var(--muted);font-size:11px;margin-top:18px;border-top:1px solid var(--line);padding-top:15px}@media(max-width:780px){.two{grid-template-columns:1fr}.stats{grid-template-columns:repeat(2,1fr)}header{align-items:flex-start;flex-direction:column}}
</style></head><body><main>
<header><div><div class="eyebrow">OASIS // ROOT0 // MOTHER KERNEL // RELEASE 166</div><h1>Witnessed Policy Control</h1><div class="sub">Hysteresis · drift detection · signed external decision pin · fail-closed recovery</div></div><div class="status">● 0e / 45 CHECKS PASS</div></header>
<section class="stats"><div class="stat"><strong>45/45</strong><span>NEW SECURITY CHECKS</span></div><div class="stat"><strong>1,000</strong><span>SYNTHETIC DRIFT WINDOWS</span></div><div class="stat"><strong>3</strong><span>POLICY TRANSITIONS / FOUR REGIMES</span></div><div class="stat"><strong>15/15</strong><span>INHERITED FAULT CHECKS</span></div></section>
<section class="two"><div class="panel"><h2>ROOT0 DECISION PIPE</h2><svg role="img" aria-label="Signed authority protects policy switching and durable recovery" viewBox="0 0 850 390"><defs><marker id="arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6" fill="none" stroke="#75cb90"/></marker></defs><g stroke="#5dc889" stroke-width="1.3" fill="none" marker-end="url(#arrow)"><path d="M425 58V94"/><path d="M425 147V177"/><path d="M425 236V268"/><path d="M425 324V358"/><path d="M280 204H130V270"/><path d="M570 204H720V270"/></g><g font-size="14" text-anchor="middle" font-weight="700"><rect x="250" y="6" width="350" height="52" rx="8" fill="#133c28" stroke="#4fac76"/><text x="425" y="38" fill="#e0ffe8">SIGNED SOURCE + ROOT0</text><rect x="247" y="94" width="355" height="53" rx="8" fill="#173020" stroke="#4fac76"/><text x="425" y="126" fill="#e0ffe8">MONITOR + HYSTERESIS</text><rect id="decision-node" x="285" y="177" width="280" height="59" rx="8" fill="#19482d" stroke="#68ee9b"/><text id="decision-label" x="425" y="211" fill="#dcffe6">SIGNED TRANSITION</text><rect x="5" y="270" width="250" height="54" rx="8" fill="#10291d" stroke="#5a9771"/><text x="130" y="303" fill="#e0ffe8">EXTERNAL PIN HEAD</text><rect x="600" y="270" width="245" height="54" rx="8" fill="#10291d" stroke="#5a9771"/><text x="722" y="303" fill="#e0ffe8">Ed25519 RESOURCE PROOF</text><rect x="280" y="268" width="290" height="56" rx="8" fill="#123d28" stroke="#4fac76"/><text x="425" y="301" fill="#e0ffe8">DURABLE CURSOR + FSYNC</text><rect x="250" y="358" width="350" height="28" rx="6" fill="#0c2419" stroke="#44845a"/><text x="425" y="378" fill="#a0f5c1" font-size="12">NEXT VERIFIED</text></g></svg><div class="legend"><span><span class="dot" style="background:#59f19b"></span>verified</span><span><span class="dot" style="background:#ffbc78"></span>policy drift</span><span><span class="dot" style="background:#f78c9e"></span>fail closed</span></div></div><div class="panel"><h2>FAULT-INJECTION SCENARIOS</h2><div class="buttons" id="scenario-buttons"></div><div class="actions"><button id="export-btn">↗ Export JSON</button><button id="reset-btn">↺ Reset viewer</button></div></div></section>
<section class="two"><div class="panel"><h2 id="scenario-title">Nominal recovery</h2><div id="scenario-pill" class="pill">VERIFIED</div><div class="sub" id="scenario-description">Signed quorum and resource continuity verified.</div><div style="margin-top:19px;font-size:12px">Observed performance vs verified baseline <strong id="ratio-text" style="float:right;color:var(--green)">114%</strong></div><div class="meter"><div class="fill" id="ratio-fill"></div></div><div class="terminal" id="terminal"></div></div><div class="panel"><h2>POLICY THRESHOLDS</h2><div class="terminal">bad:       &lt; 0.88 × baseline
recover:   &gt; 1.18 × baseline
weak:      3 consecutive windows
strong:    4 consecutive windows
dwell:     ≥ 48 committed rows
cooldown:  ≥ 96 observed rows
drift:     fast EMA &lt; .91 × slow
promotion: verified holdout only</div><p class="sub" style="font-size:12px">Simulated scenarios are a UI illustration; the real test gate and evidence are provided in the executable archive.</p></div></section>
<footer>Testing boundary: three signed policy transitions in 1,000 deterministic synthetic observations; one mTLS live recovery. All processes share one host. Signed rollback pins do not constitute independently hosted consensus or measurement attestation. Full historic regression chain not rerun.</footer>
</main><script>
const scenarios=__SCENARIOS__;
const report=__REPORT__;
let active=0;
const el=id=>document.getElementById(id);
function render(i){active=i;const s=scenarios[i];const b=el('scenario-buttons');Array.from(b.children).forEach((n,j)=>{n.classList.toggle('active',j===i);n.setAttribute('aria-pressed',j===i?'true':'false')});el('scenario-title').textContent=s.name;el('scenario-description').textContent=s.detail;el('scenario-pill').textContent=s.status;el('scenario-pill').className='pill'+(s.ok?'':' blocked');el('ratio-text').textContent=Math.round(s.ratio*100)+'%';el('ratio-fill').style.width=Math.min(100,s.ratio/1.5*100)+'%';el('ratio-fill').style.background=s.ok?'linear-gradient(90deg,#328d5c,#5bf5a4)':'#d68a95';el('decision-node').setAttribute('stroke',s.ok?'#68ee9b':'#f3a4ac');el('decision-label').textContent=s.ok?'SIGNED TRANSITION':'REJECT / QUARANTINE';el('terminal').textContent='> scenario   '+s.name+'\n> measured   '+s.ratio.toFixed(2)+' × verified baseline\n> policy     '+s.mode+'\n> witness    '+s.status+'\n> result     '+(s.ok?'CONTINUE / VERIFIED':'HALT / FAIL CLOSED');}
scenarios.forEach((s,i)=>{const button=document.createElement('button');button.type='button';button.textContent=s.name;button.setAttribute('aria-label','Select '+s.name);button.onclick=()=>render(i);el('scenario-buttons').append(button)});
el('reset-btn').onclick=()=>render(0);
el('export-btn').onclick=()=>{const text=JSON.stringify({schema:'oasis.sheet166.dashboard.v1',selection:scenarios[active],release:report},null,2);const blob=new Blob([text],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='SHEET166-scenario.json';document.body.append(a);a.click();a.remove();URL.revokeObjectURL(url)};
render(0);
</script></body></html>'''
html=html.replace('__SCENARIOS__',js).replace('__REPORT__',json.dumps({'checks':r['checks'],'syntheticWindows':r['loadReport']['windows'],'syntheticTransitions':r['loadReport']['changes'],'networkRows':r['network']['rows'],'networkSeconds':r['network']['elapsedSeconds']}))
(p/'index.html').write_text(html)
print('HTML bytes',len(html),'scenarios',len(scenarios))
