'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {BatchStore}=require('./batch162'),{Store}=require('./baseline161/baseline160/indexed160');
const P=require('./baseline161/baseline160/baseline159/baseline158/baseline157/baseline156/baseline155/baseline154/baseline153/baseline152/baseline151/baseline150/baseline149/baseline148/baseline147/baseline146/protocol146');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'oasis162-unit-'));let checks=0;const ok=(s,fn)=>{fn();console.log('PASS',++checks,s)};try{
 const a=new BatchStore(path.join(tmp,'new'),'ROOT'),b=new Store(path.join(tmp,'old'),'ROOT');a.init();b.init();const rows=Array.from({length:8},(_,i)=>({txid:'tx'+i,payload:'d'+i}));a.batch(rows,{expectedIndex:0});for(const r of rows)b.append(r.payload,r.txid);ok('8-row batch produces byte-identical root',()=>assert.equal(a.read().root,b.read().root));ok('8-row batch produces identical segment digest',()=>assert.equal(a.read().segments[0].digest,b.read().segments[0].digest));ok('one segment write, one head write',()=>assert.deepEqual([a.batchMetrics.segmentCommits,a.batchMetrics.headCommits],[1,1]));ok('reject repeated batch cursor',()=>assert.throws(()=>a.batch(rows,{expectedIndex:0}),/S162_BATCH_CURSOR/));ok('reject forged row hash',()=>assert.throws(()=>a.batch([{payload:'hi',txid:'a',hash:'f'.repeat(64)}]),/S162_ROW_HASH/));
 for(let i=8;i<254;i++)a.append('d'+i,'tx'+i);
 ok('cross-boundary 8-row commit fails closed',()=>assert.throws(()=>a.batch(rows,{expectedIndex:254}),/S162_BATCH_CROSSES_SEGMENT/));
 a.batch([{txid:'tx254',payload:'d254'},{txid:'tx255',payload:'d255'}]);a.batch([{txid:'tx256',payload:'d256'}]);ok('segment boundary and upper index valid',()=>assert.equal(a.read().count,257));ok('inclusion valid at boundary',()=>assert.equal(a.inclusion(256).count,257));
 const c=new BatchStore(path.join(tmp,'crash'),'CR');c.init();ok('crash between segment and head detected',()=>assert.throws(()=>c.batch(rows,{crashAfterSegment:true}),/S162_INJECT_AFTER_SEGMENT/));ok('store fails closed with orphan',()=>assert.throws(()=>c.read(),/S160_ORPHAN_OR_MISSING_SEGMENT/));const orphan=c.inspectOrphan();ok('orphan records are exact batch',()=>assert.equal(orphan.recordHashes.length,8));
 const keys=Object.fromEntries(['a','b','c'].map(x=>[x,crypto.generateKeyPairSync('ed25519')]));const sig=id=>({id,signature:P.sign(keys[id].privateKey,'S162:RECOVERY',orphan)}),pub=Object.fromEntries(Object.entries(keys).map(([k,v])=>[k,v.publicKey]));
 ok('one operator denied',()=>assert.throws(()=>c.reconcileOrphan(orphan,[sig('a')],pub),/S162_RECOVERY_QUORUM/));ok('duplicate operator denied',()=>assert.throws(()=>c.reconcileOrphan(orphan,[sig('a'),sig('a')],pub),/S162_RECOVERY_SIGNATURE/));ok('forged signature denied',()=>assert.throws(()=>c.reconcileOrphan(orphan,[sig('a'),{...sig('b'),signature:'fake'}],pub),/S162_RECOVERY_SIGNATURE/));c.reconcileOrphan(orphan,[sig('a'),sig('b')],pub);ok('orphan recovered exactly once',()=>assert.equal(c.read().count,8));ok('recovery no longer has orphan',()=>assert.equal(c.inspectOrphan(),null));ok('no repeat of prior approval',()=>assert.throws(()=>c.reconcileOrphan(orphan,[sig('a'),sig('b')],pub),/S162_ORPHAN_CHANGED/));
 const d=new BatchStore(path.join(tmp,'headcrash'),'DC');d.init();ok('crash after durable head simulated',()=>assert.throws(()=>d.batch(rows,{crashAfterHead:true}),/S162_INJECT_AFTER_HEAD/));ok('eight rows retained after post-head crash',()=>assert.equal(d.read().count,8));
 console.log('SHEET162 UNIT '+checks+'/'+checks+' PASS');
}catch(e){console.error(e.stack);process.exitCode=1;}finally{fs.rmSync(tmp,{recursive:true,force:true});}
