#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const P=require('./baseline151/baseline150/baseline149/baseline148/baseline147/baseline146/protocol146');
const {AnchoredBridge}=require('./bridge152');
const {verifyGrant,quorumCurrent}=require('./baseline151/baseline150/baseline149/baseline148/proof148');
let count=0;const pass=(s,fn)=>{fn();console.log('PASS',++count,s)},step=async(s,fn)=>{await fn();console.log('PASS',++count,s)},fails=async(s,fn,re)=>step(s,async()=>assert.rejects(fn,re));
const J=require('./baseline151/baseline150/journal150');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'s150-')),file=(...p)=>path.join(root,...p);
const openssl=(...args)=>cp.execFileSync('openssl',args,{cwd:root,stdio:'pipe'});
function cert(name){openssl('req','-new','-newkey','rsa:2048','-nodes','-keyout',name+'.key','-out',name+'.csr','-subj','/CN=localhost');fs.writeFileSync(file(name+'.ext'),'subjectAltName=DNS:localhost,IP:127.0.0.1\nkeyUsage=digitalSignature,keyEncipherment\nextendedKeyUsage=clientAuth,serverAuth\n');openssl('x509','-req','-in',name+'.csr','-CA','ca.crt','-CAkey','ca.key','-CAcreateserial','-out',name+'.crt','-days','2','-sha256','-extfile',name+'.ext');return{key:file(name+'.key'),cert:file(name+'.crt'),ca:file('ca.crt'),certPin:new crypto.X509Certificate(fs.readFileSync(file(name+'.crt'))).fingerprint256.replaceAll(':','').toLowerCase()};}
function keys(name){const x=crypto.generateKeyPairSync('ed25519'),priv=file(name+'.priv'),pub=file(name+'.pub');fs.writeFileSync(priv,x.privateKey.export({type:'pkcs8',format:'pem'}),{mode:0o600});fs.writeFileSync(pub,x.publicKey.export({type:'spki',format:'pem'}));return{priv,pub,privateKey:x.privateKey};}
let children=[];
async function spawn(script,cfg,label){const config=file(label+'-'+crypto.randomUUID()+'.json');fs.writeFileSync(config,JSON.stringify(cfg));const env={...process.env,[script==='resource152.js'?'S150_RESOURCE_CONFIG':script==='anchor-server152.js'?'S152_ANCHOR_CONFIG':'S152_REPLICA_CONFIG']:config};const proc=cp.fork(path.join(__dirname,script),[],{env,stdio:['ignore','pipe','pipe','ipc']});let stderr='';proc.stderr.on('data',b=>stderr+=b);const x=await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('TIMEOUT '+stderr)),9500);proc.once('message',m=>{clearTimeout(timeout);resolve({proc,port:m.port,label,error:()=>stderr});});proc.once('exit',c=>{clearTimeout(timeout);reject(Error('EXIT '+c+' '+stderr));});});children.push(x);return x;}
async function stop(x){if(!x||x.proc.exitCode!==null||x.proc.killed)return;await new Promise(r=>{const t=setTimeout(()=>{x.proc.kill('SIGKILL');r();},1300);x.proc.once('exit',()=>{clearTimeout(t);r();});x.proc.send('stop');});}
(async()=>{try{
 openssl('req','-x509','-new','-newkey','rsa:2048','-nodes','-keyout','ca.key','-out','ca.crt','-days','2','-subj','/CN=S148-Test-CA');
 const ids=Object.fromEntries(['red','blue','green','alpha','beta','observer','resource','writer','rogue','anchor'].map(id=>[id,cert(id)]));
 const signers=Object.fromEntries(['red','blue','green','resource','pin','anchor','op1','op2','op3'].map(id=>[id,keys(id+'-ed')]));
 const pubKeys=Object.fromEntries(['red','blue','green'].map(id=>[id,signers[id].pub]));
 const members=Object.fromEntries(Object.entries(pubKeys).map(([id,p])=>[id,{publicKey:p}]));
 const leaders={alpha:{certPin:ids.alpha.certPin},beta:{certPin:ids.beta.certPin},observer:{certPin:ids.resource.certPin}};
 const G=require('./anchor-proof152');
 const {Ledger}=require('./baseline151/ledger151');
 const {review,DOMAIN}=require('./reconcile152');
 const ledger=new Ledger(file('segment-journal151'),'resource',signers.resource.privateKey);
 ledger.init();
 const anchorCfg={...ids.anchor,file:file('anchor-floor','checkpoint.json'),resourceId:'resource',resourcePublic:signers.resource.pub,anchorPrivate:signers.anchor.priv,anchorPublic:signers.anchor.pub,controlPin:ids.writer.certPin,readPins:[ids.red.certPin,ids.blue.certPin,ids.green.certPin,ids.writer.certPin]};
 let anchorSrv=await spawn('anchor-server152.js',anchorCfg,'anchor');
 const ctl=(url,body={})=>P.rpc({port:anchorSrv.port,key:ids.writer.key,cert:ids.writer.cert,ca:ids.writer.ca,serverPin:ids.anchor.certPin},url,body);
 let anchored=await ctl('/init',{checkpoint:ledger.checkpoint()});
 const genesis=structuredClone(anchored);
 const nodes={},configs={};
 for(const id of ['red','blue','green']){
  const body={schema:'oasis.sheet152.replica.v1',seq:0,head:'0'.repeat(64)};
  const pin=file(id+'-floor','pin.json');P.atomic(pin,{schema:body.schema,body,signature:P.sign(signers.pin.privateKey,'S147:EXTERNAL_PIN',body)});
  configs[id]={id,...ids[id],signKey:signers[id].priv,members,leaders,stateFile:file(id,'state.json'),floorFile:pin,floorPublicKey:signers.pin.pub,resourcePublicKeys:{resource:signers.resource.pub},anchorPublicKey:signers.anchor.pub,anchor:{port:anchorSrv.port,certPin:ids.anchor.certPin}};
  nodes[id]=await spawn('replica152.js',configs[id],id);
 }
 const replicas=()=>Object.fromEntries(Object.entries(nodes).filter(([,n])=>n.proc.exitCode===null).map(([id,x])=>[id,{port:x.port,certPin:ids[id].certPin}]));
 const leader=(id)=>new AnchoredBridge({leaderId:id,identity:ids[id],replicas:replicas(),publicKeys:pubKeys,resourcePublicKeys:{resource:signers.resource.pub}});
 let A=leader('alpha');await A.elect();
 let resourceCfg={...ids.resource,resourceId:'resource',signKey:signers.resource.priv,stateFile:file('resource','state.json'),writerPin:ids.writer.certPin,observerId:'observer',replicaPublicKeys:pubKeys,replicas:replicas(),testMode:true};
 const pinBody={resourceId:'resource',sequence:0,head:'0'.repeat(64)};
 resourceCfg.floorFile=file('independent-pin','pin.json');resourceCfg.floorPublicKey=signers.pin.pub;
 const putFloor=(body)=>P.atomic(resourceCfg.floorFile,{body,signature:P.sign(signers.pin.privateKey,'S148:RESOURCE_FLOOR',body)});
 putFloor(pinBody);
 let resource=await spawn('resource152.js',resourceCfg,'resource');
 const writer=(body,iden=ids.writer)=>P.rpc({port:resource.port,key:iden.key,cert:iden.cert,ca:iden.ca,serverPin:ids.resource.certPin},'/write',body);
 const status=()=>P.load(resourceCfg.stateFile);
 const req=(txid,epoch=1)=>({txid,resourceId:'resource',operationId:'write',value:'message-'+txid,epoch});
  const opKeys={op1:fs.readFileSync(signers.op1.pub),op2:fs.readFileSync(signers.op2.pub),op3:fs.readFileSync(signers.op3.pub)};
 const torn=new Ledger(file('torn'),'resource',signers.resource.privateKey);torn.init();
 await fails('torn segment cannot auto-replay',async()=>{assert.throws(()=>torn.append('persisted',{crashBeforeHead:true}),/INJECTED_CRASH/);torn.read();},/SEGMENT_COUNT_OR_TORN_WRITE/);
 const tornRec=P.load(torn.segment(0)).records[0];
 const plan={schema:'oasis.sheet152.review.v1',resourceId:'resource',headCount:0,headRoot:torn.read.bind?require('./baseline151/merkle151').EMPTY:'',appendHash:tornRec.hash,anchorDigest:P.sha(genesis)};
 const approvals=['op1','op2'].map(id=>({id,signature:P.sign(signers[id].privateKey,DOMAIN,plan)}));
 await fails('one operator cannot resolve torn head',async()=>review(file('torn'),'resource',genesis,fs.readFileSync(signers.anchor.pub),opKeys,plan,approvals.slice(0,1)),/RECOVERY_QUORUM_REQUIRED/);
 await fails('forged operator vote cannot resolve torn head',async()=>review(file('torn'),'resource',genesis,fs.readFileSync(signers.anchor.pub),opKeys,plan,[approvals[0],{id:'op2',signature:'AAAA'}]),/RECOVERY_VOTE_INVALID/);
 pass('two distinct operators resolve precisely one extant record',()=>assert.equal(review(file('torn'),'resource',genesis,fs.readFileSync(signers.anchor.pub),opKeys,plan,approvals).count,1));
 pass('reviewed repair leaves original payload and one record',()=>assert.equal(torn.read().records[0].payload,'persisted'));
 await fails('recovery decision cannot execute twice',async()=>review(file('torn'),'resource',genesis,fs.readFileSync(signers.anchor.pub),opKeys,plan,approvals),/RECOVERY_NOT_SINGLE_TORN_APPEND/);
 pass('network has three mTLS replicas',()=>assert.equal(Object.keys(nodes).length,3));
 pass('anchor signer uses a distinct Ed25519 key',()=>assert.notEqual(fs.readFileSync(signers.resource.pub,'utf8'),fs.readFileSync(signers.anchor.pub,'utf8')));
 pass('separate process signs the genesis checkpoint',()=>assert.ok(P.verify(fs.readFileSync(signers.anchor.pub),'S151:ANCHOR',anchored.body,anchored.signature)));
 await fails('anchor refuses forged controller TLS certificate',()=>P.rpc({...ids.rogue,port:anchorSrv.port,serverPin:ids.anchor.certPin},'/advance',{checkpoint:{}}),/TLS_PEER_NOT_PINNED/);
 const one=req('one');const grant=await A.begin(one),written=await writer({...one,grant});
 pass('S150 resource performs exactly one durable write',()=>assert.equal(status().sequence,1));
 await fails('unanchored completion rejected by bridge',()=>A.complete('one',written.receipt,written.journalProof),/ANCHOR_PROOF_REQUIRED/);
 const opUnanchored={type:'COMPLETE',txid:'one',receiptHash:P.sha(written.receipt),receipt:written.receipt,journalProof:written.journalProof};
 const start=await A.state();
 const makeProposal=(op,who='alpha',term=A.term,s=start)=>({term,leaderId:who,index:s.seq+1,prev:s.head,op});
 const forgedVotes=(proposal)=>['red','blue'].map(nodeId=>{const body={nodeId,digest:P.sha(proposal),term:proposal.term,index:proposal.index,prev:proposal.prev,leaderId:proposal.leaderId};return{body,signature:P.sign(signers[nodeId].privateKey,'S147:PREPARE',body)};});
 await fails('replica refuses unanchored prepare',()=>A.ask('red','/prepare',{proposal:makeProposal(opUnanchored)}),/ANCHOR_LIVE_UNAVAILABLE/);
 await fails('replica refuses unanchored commit with forged votes',()=>A.ask('red','/commit',{proposal:makeProposal(opUnanchored),votes:forgedVotes(makeProposal(opUnanchored))}),/ANCHOR_LIVE_UNAVAILABLE/);
 const record=ledger.append(G.payload(written.receipt,written.journalProof));
 pass('S151 journal payload binds the S150 receipt and checkpoint',()=>assert.equal(record.record.payload,G.payload(written.receipt,written.journalProof)));
 const cp1=ledger.checkpoint(anchored);anchored=await ctl('/advance',{checkpoint:cp1,proof:ledger.extension(0)});
 const good=G.bundle(ledger,written.receipt,written.journalProof,cp1,anchored);
 pass('two signed independent checkpoint chains verify',()=>assert.equal(G.verifyStatic(written.receipt,written.journalProof,good,fs.readFileSync(signers.resource.pub),fs.readFileSync(signers.anchor.pub)).count,1));
 const requestOp={...opUnanchored,anchorProof:good};
 pass('direct verifier rejects forged signed anchor',()=>assert.throws(()=>G.verifyStatic(written.receipt,written.journalProof,{...good,snapshot:{...good.snapshot,signature:'AAAA'}},fs.readFileSync(signers.resource.pub),fs.readFileSync(signers.anchor.pub)),/ANCHOR_SNAPSHOT_SIGNATURE_INVALID/));
 await fails('forged anchor signature refused by replica',()=>A.ask('red','/prepare',{proposal:makeProposal({...requestOp,anchorProof:{...good,snapshot:{...good.snapshot,signature:'AAAA'}}})}),/ANCHOR_STALE_LIVE_HEAD/);
 await fails('wrong linked journal record rejected',()=>A.ask('red','/prepare',{proposal:makeProposal({...requestOp,anchorProof:{...good,record:{...good.record,payload:'not-a-receipt'}}})}),/ANCHOR_BINDING_MISMATCH/);
 await fails('tampered anchor inclusion witness rejected',()=>A.ask('red','/prepare',{proposal:makeProposal({...requestOp,anchorProof:{...good,proof:{...good.proof,recordHash:'f'.repeat(64)}}})}),/ANCHOR_INCLUSION_BINDING_INVALID/);
 await fails('substituted S150 journal proof rejected',()=>A.ask('red','/prepare',{proposal:makeProposal({...requestOp,journalProof:{...written.journalProof,checkpoint:{...written.journalProof.checkpoint,signature:'AAAA'}}})}),/CHECKPOINT_SIGNATURE_INVALID/);
 await fails('altered S150 receipt rejected despite valid anchor',()=>A.ask('red','/prepare',{proposal:makeProposal({...requestOp,receipt:{...written.receipt,signature:'AAAA'}})}),/REPLICA_RECEIPT_BAD_SIGNATURE/);
 const competing=structuredClone(good);competing.record.sequence=2;
 await fails('wrong S151 sequence rejected',()=>A.ask('red','/prepare',{proposal:makeProposal({...requestOp,anchorProof:competing})}),/ANCHOR_BINDING_MISMATCH/);
 await step('replicas independently accept current anchored completion',async()=>assert.equal((await A.complete('one',written.receipt,written.journalProof,good)).seq,2));
 pass('S152 replica independently persists anchored high water',()=>{for(const id of ['red','blue','green'])assert.equal(P.load(configs[id].stateFile).anchorPins.resource.count,1);});
 await fails('duplicate completion blocked by immutable quorum history',()=>A.complete('one',written.receipt,written.journalProof,good),/RECEIPT_NO_PENDING_QUORUM/);
 // Segment rollover: 151 has a separate scalable log; 150 resource remains bounded.
 for(let i=0;i<258;i++)ledger.append('rollover:'+i);
 pass('signed record continuity spans three S151 segments',()=>assert.equal(ledger.read().head.count,259));
 const cp259=ledger.checkpoint(anchored),savedOldAnchor=structuredClone(anchored);
 anchored=await ctl('/advance',{checkpoint:cp259,proof:ledger.extension(1)});
 pass('anchor serial advances without replacing old checkpoint',()=>assert.equal(anchored.body.serial,2));
 pass('old receipt remains included under current S151 head',()=>require('./baseline151/merkle151').verifyInclusion(ledger.inclusion(0),cp259.body.root,ledger.read().records[0].hash));
 const two=req('two'),g2=await A.begin(two);
 await fails('old epoch cannot cut over with pending grant',()=>A.run({type:'CUTOVER',epoch:2}),/PREPARE_QUORUM_NOT_REACHED/);
 let crash=await writer({...two,grant:g2,crashAfterWrite:true}).catch(e=>e);
 pass('real resource process crashed after durable mutation',()=>assert.ok(crash instanceof Error));
 pass('durable resource has exactly two rows after crash',()=>assert.equal(status().sequence,2));
 resource=await spawn('resource152.js',resourceCfg,'resource-restarted');
 const retry=await writer({...two,grant:g2});
 pass('restart returned original record rather than mutating twice',()=>assert.equal(retry.receipt.body.recordHash,status().records[1].hash));
 const old=A;A=leader('beta');await step('new authority leader elected after resource crash',async()=>assert.equal((await A.elect()).term,2));
 await fails('superseded leader cannot finalize',()=>old.complete('two',retry.receipt,retry.journalProof,good),/RECEIPT_NO_PENDING_QUORUM|NOT_ELECTED|PREPARE_QUORUM_NOT_REACHED/);
 const r2=ledger.append(G.payload(retry.receipt,retry.journalProof));
 pass('second transaction appended once in S151',()=>assert.equal(r2.record.sequence,260));
 const cp260=ledger.checkpoint(anchored);anchored=await ctl('/advance',{checkpoint:cp260,proof:ledger.extension(259)});
 const good2=G.bundle(ledger,retry.receipt,retry.journalProof,cp260,anchored);
 const oldProof={...good2,snapshot:savedOldAnchor};
 const op2={type:'COMPLETE',txid:'two',receiptHash:P.sha(retry.receipt),receipt:retry.receipt,journalProof:retry.journalProof,anchorProof:oldProof};
 const now=await A.state(),proposal2=(o)=>makeProposal(o,'beta',A.term,now);
 await fails('replica checks current signed anchor over live mTLS at prepare',()=>A.ask('red','/prepare',{proposal:proposal2(op2)}),/ANCHOR_STALE_LIVE_HEAD/);
 await fails('replica checks anchor on direct commit with fabricated majority votes',()=>A.ask('red','/commit',{proposal:proposal2(op2),votes:forgedVotes(proposal2(op2))}),/ANCHOR_STALE_LIVE_HEAD/);
 await step('signed rollover inclusion verified during new-leader completion',async()=>assert.equal((await A.complete('two',retry.receipt,retry.journalProof,good2)).seq,4));
 await step('cutover allowed only after both receipts verified',async()=>assert.equal((await A.run({type:'CUTOVER',epoch:2})).epoch,2));
 await fails('old membership epoch cannot create a resource grant',()=>A.begin(req('stale',1)),/STALE_REQUEST_EPOCH/);
 const stable=P.load(configs.red.stateFile),corrupt=structuredClone(stable);
 corrupt.journal.find(x=>x.proposal.op.type==='COMPLETE').proposal.op.anchorProof.snapshot.signature='AAAA';
 P.atomic(configs.red.stateFile,corrupt);
 await fails('replica replays and rejects a mutated certified history',()=>A.ask('red','/state'),/INVALID_VOTE_SIGNATURE/);
 P.atomic(configs.red.stateFile,stable);
 await step('restored signed journal replays successfully',async()=>assert.equal((await A.ask('red','/state')).body.seq,5));
 await stop(anchorSrv);
 await fails('anchor outage blocks replica decision servicing',()=>A.ask('red','/state'),/ECONNREFUSED|RPC_TIMEOUT|socket hang up/);
 pass('authority still retains two committed receipts on disk',()=>assert.equal(P.load(configs.blue.stateFile).completed.length,2));
 const report={schema:'oasis.sheet152.gate.v1',newChecks:count,passed:true,realTLS:true,replicas:3,resourceProcesses:2,anchorProcess:true,segmented151Count:260,s150ResourceCount:2,signatureReplay:true,crashRecovered:true,partialPartitionFailClosed:true,reviewedTornRecovery:true};
 fs.writeFileSync(path.join(__dirname,'new-test-report.json'),JSON.stringify(report,null,2)+'\n');
 console.log(`SHEET152 NEW PASS ${count}/${count}`);
} catch(e){console.error('FAIL AFTER '+count, e.stack||e);process.exitCode=1;}finally{for(const x of children.reverse())await stop(x).catch(()=>{});fs.rmSync(root,{recursive:true,force:true});}})();
