'use strict';
// SHEET 164 -- reproducible 2x2x2 factorial + holdout + process-kill recovery
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {performance}=require('node:perf_hooks');
const {BatchStore}=require('./baseline163/baseline162/batch162');
const P=require('./baseline163/baseline162/baseline161/baseline160/baseline159/baseline158/baseline157/baseline156/baseline155/baseline154/baseline153/baseline152/baseline151/baseline150/baseline149/baseline148/baseline147/baseline146/protocol146');
const V=require('./baseline163/baseline162/baseline161/proof161');
const Pipeline=require('./pipeline164');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'oasis-s164-'));
const f=(...parts)=>path.join(root,...parts);let checks=0;let processes=[];
function test(label,fn){fn();checks++;console.log('PASS',checks,label);}
async function atest(label,fn){await fn();checks++;console.log('PASS',checks,label);}
const openssl=(...args)=>cp.execFileSync('openssl',args,{cwd:root,stdio:'pipe'});
function keypair(label){const k=crypto.generateKeyPairSync('ed25519');const priv=f(label+'.priv'),pub=f(label+'.pub');fs.writeFileSync(priv,k.privateKey.export({format:'pem',type:'pkcs8'}));fs.writeFileSync(pub,k.publicKey.export({format:'pem',type:'spki'}));return {...k,priv,pub};}
function cert(label){openssl('req','-new','-newkey','rsa:2048','-nodes','-keyout',label+'.key','-out',label+'.csr','-subj','/CN=localhost');fs.writeFileSync(f(label+'.ext'),'subjectAltName=DNS:localhost,IP:127.0.0.1\nkeyUsage=digitalSignature,keyEncipherment\nextendedKeyUsage=clientAuth,serverAuth\n');openssl('x509','-req','-in',label+'.csr','-CA','ca.crt','-CAkey','ca.key','-CAcreateserial','-out',label+'.crt','-days','2','-sha256','-extfile',label+'.ext');return {key:f(label+'.key'),cert:f(label+'.crt'),ca:f('ca.crt'),certPin:new crypto.X509Certificate(fs.readFileSync(f(label+'.crt'))).fingerprint256.replaceAll(':','').toLowerCase()};}
const ID='OASIS-SHEET164';let certs,keys,anchorKey,source,sourceHead,sources,seedDir;
const row=i=>({txid:'s164:'+i,payload:'sample-'+i});
function fill(store,start,end){for(let i=start;i<end;){const k=Math.min(8,256-i%256,end-i);store.batch(Array.from({length:k},(_,j)=>row(i+j)));i+=k;}}
function setup(){openssl('req','-x509','-new','-newkey','rsa:2048','-nodes','-keyout','ca.key','-out','ca.crt','-days','2','-subj','/CN=OASIS-S164-CA');certs=Object.fromEntries(['client','red','green','blue'].map(n=>[n,cert(n)]));keys=Object.fromEntries(['red','green','blue'].map(n=>[n,keypair(n)]));anchorKey=keypair('floor');const store=new BatchStore(f('source-red'),ID);store.init();fill(store,0,384);sourceHead=store.read();fs.cpSync(f('source-red'),f('source-green'),{recursive:true});const prefix=new BatchStore(f('seed256'),ID);prefix.init();fill(prefix,0,256);seedDir=f('seed256');}
function config(name,dir,session){return {nodeId:name,resourceId:ID,...certs[name],dir,signKey:keys[name].priv,anchorPublicKey:anchorKey.pub,peerPublicKeys:Object.fromEntries(Object.entries(keys).map(([n,v])=>[n,v.pub])),clientPin:certs.client.certPin,session:f('sessions',session+'-'+name+'.json'),externalPin:f('pins',session+'-'+name+'.json'),quarantine:f('quarantine',session+'-'+name+'.txt')};}
async function spawn(conf,label){P.atomic(f('configs',label+'.json'),conf);let err='';const proc=cp.fork(path.join(__dirname,'baseline163/node163.js'),[],{env:{...process.env,S163_CONFIG:f('configs',label+'.json')},stdio:['ignore','pipe','pipe','ipc']});proc.stderr.on('data',chunk=>{err+=chunk;});const port=await new Promise((resolve,reject)=>{let resolved=false;const timer=setTimeout(()=>{if(!resolved){resolved=true;reject(Error('S164_START_TIMEOUT '+label+' '+err));}},12000);proc.once('message',m=>{if(!resolved){resolved=true;clearTimeout(timer);resolve(m.port);}});proc.once('exit',code=>{if(!resolved){resolved=true;clearTimeout(timer);reject(Error('S164_START_EXIT '+code+' '+err));}});});const out={proc,port,label,conf};processes.push(out);return out;}
async function stop(x){if(!x||x.proc.exitCode!==null||x.proc.signalCode!==null)return;await new Promise(resolve=>{let settled=false;function done(){if(!settled){settled=true;clearTimeout(timer);resolve();}}const timer=setTimeout(()=>{try{x.proc.kill('SIGKILL');}catch{}done();},800);x.proc.once('exit',done);try{x.proc.send('stop',e=>{if(e){try{x.proc.kill('SIGKILL');}catch{}done();}});}catch{try{x.proc.kill('SIGKILL');}catch{}done();}});}
function endpoints(peerNodes,blue){return Object.fromEntries(Object.entries({...peerNodes,blue}).map(([n,m])=>[n,{port:m.port,serverPin:certs[n].certPin}]));}
function makeClient(peerNodes,blue,conf,block){return Pipeline.make({identity:certs.client,nodes:endpoints(peerNodes,blue),keys:Object.fromEntries(Object.entries(keys).map(([n,v])=>[n,v.publicKey])),anchor:V.signAnchor(V.anchorBody(ID,sourceHead,100),anchorKey.privateKey),anchorKey:anchorKey.publicKey,fetchWindow:conf.window,batchMode:conf.batch===4?'fixed4':'fixed8',reuseTls:conf.reuseTls,delayFetch:offset=>3+((offset*7+block*11)%12)});}
let seq=0;async function scenario(peers,conf,block,{crash=false,prefix=256}={}){seq++;const name='case'+seq,dir=f(name,'blue');fs.mkdirSync(path.dirname(dir),{recursive:true});if(prefix===256)fs.cpSync(seedDir,dir,{recursive:true});else {const s=new BatchStore(dir,ID);s.init();fill(s,0,prefix);}
 let blue=await spawn({...config('blue',dir,name),...(crash?{crashAfterHeadOnce:f(name,'crash-marker')}: {})},name+'-blue');let client=makeClient(peers,blue,conf,block);let failed=false;const initial=prefix;
 try{if(crash){try{await client.sync('blue');}catch(e){failed=true;}await atest('injected worker crash interrupts acknowledgement',async()=>{assert(failed);assert(blue.proc.exitCode!==null||blue.proc.signalCode!==null||fs.existsSync(f(name,'crash-marker')));const h=new BatchStore(dir,ID).read();assert(h.count>initial);});await stop(blue);blue=await spawn(blue.conf,name+'-blue-restart');client.close();client=makeClient(peers,blue,conf,block);}
 const starts=[];const start=performance.now();const outcome=await client.sync('blue',{onCommit:(a,b)=>starts.push([a,b])});const seconds=(performance.now()-start)/1000;const after=new BatchStore(dir,ID).read();await atest('verified exact source Merkle root '+name,async()=>{assert.equal(after.count,sourceHead.count);assert.equal(after.root,sourceHead.root);assert.equal(after.lastRecordHash,sourceHead.lastRecordHash);});
 test('durable commit order and segment boundaries '+name,()=>{for(let i=0;i<starts.length;i++){if(i)assert.equal(starts[i-1][1],starts[i][0]);assert(starts[i][1]-starts[i][0]<=8);assert(Math.floor(starts[i][0]/256)===Math.floor((starts[i][1]-1)/256));}});
 const verifiedStatus=await client.rpc('blue','/status161');test('mTLS and actual remote proof metrics are bounded '+name,()=>{assert(P.verify(keys.blue.publicKey,'S161:STATUS',verifiedStatus.body,verifiedStatus.signature));assert(outcome.pipeline.maxInFlight<=conf.window);assert(outcome.metrics.handshakes>=1);assert(outcome.metrics.requests>0);assert.equal(verifiedStatus.body.recordHashesReplayed,0);});
 const result={name,block,window:conf.window,batch:conf.batch,reuseTls:conf.reuseTls,crash,prefix,rows:sourceHead.count-prefix,seconds:+seconds.toFixed(4),recordsPerSecond:+((sourceHead.count-prefix)/seconds).toFixed(2),tlsConnections:outcome.metrics.handshakes,requests:outcome.metrics.requests,bytes:outcome.metrics.pageBytes,maxInFlight:outcome.pipeline.maxInFlight,segmentCommits:starts.reduce((sum,[a,b])=>sum+Math.ceil((b-a)/conf.batch),0),jitterSeed:block};
 console.log('BENCHMARK164',JSON.stringify(result));return result;
 }finally{client.close();await stop(blue);}}
function rng(seed){let s=seed;return()=>{s^=s<<13;s^=s>>>17;s^=s<<5;return(s>>>0)/4294967296;};}
function shuffle(items,rand){const a=items.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(rand()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function select(rows){const byConfig=new Map();for(const r of rows){const key=[r.window,r.batch,r.reuseTls].join('/');if(!byConfig.has(key))byConfig.set(key,[]);byConfig.get(key).push(r.recordsPerSecond);}const med=x=>{const sorted=x.slice().sort((a,b)=>a-b);return sorted.length%2?sorted[(sorted.length-1)/2]:(sorted[sorted.length/2-1]+sorted[sorted.length/2])/2;};const scored=[...byConfig].map(([key,values])=>({key,medianRowsPerSecond:+med(values).toFixed(2),samples:values.length})).sort((a,b)=>b.medianRowsPerSecond-a.medianRowsPerSecond||a.key.localeCompare(b.key));const [w,b,t]=scored[0].key.split('/');return{scored,selected:{window:+w,batch:+b,reuseTls:t==='true'}};}
async function main(){test('reject concurrency window zero',()=>assert.throws(()=>Pipeline.make({fetchWindow:0}),/WINDOW_BOUNDS/));test('reject concurrency window nine',()=>assert.throws(()=>Pipeline.make({fetchWindow:9}),/WINDOW_BOUNDS/));test('4-record batch policy obeys boundary',()=>assert.equal(Pipeline.chooseBatch(254,8,1),2));test('8-record batch policy obeys boundary',()=>assert.equal(Pipeline.chooseBatch(255,8,2),1));test('zero-size proof request rejected',()=>assert.throws(()=>Pipeline.bound(5,20,0),/PAGE_BOUNDS/));test('future cursor rejected',()=>assert.throws(()=>Pipeline.bound(21,20),/PAGE_BOUNDS/));
 setup();const sources={red:await spawn(config('red',f('source-red'),'source'),'source-red'),green:await spawn(config('green',f('source-green'),'source'),'source-green')};const factorial=[];for(const window of [1,4])for(const batch of [4,8])for(const reuseTls of [false,true])factorial.push({window,batch,reuseTls});
 const rand=rng(0x164bad5);const results=[];try{for(let block=0;block<2;block++){const order=shuffle(factorial,rand);console.log('FACTORIAL164_BLOCK',block,order.map(x=>[x.window,x.batch,+x.reuseTls]));for(const conf of order)results.push(await scenario(sources,conf,block));}
  const choice=select(results);test('full factorial covers eight policies',()=>assert.equal(choice.scored.length,8));test('two replicates per policy',()=>assert(choice.scored.every(x=>x.samples===2)));test('TLS-off creates one connection per measured request',()=>assert(results.filter(x=>!x.reuseTls).every(x=>x.tlsConnections===x.requests)));test('TLS-on reuses pinned connections',()=>assert(results.filter(x=>x.reuseTls).every(x=>x.tlsConnections<=6&&x.requests>=30)));test('selector returns bounded policy',()=>{assert([1,4].includes(choice.selected.window));assert([4,8].includes(choice.selected.batch));assert.equal(typeof choice.selected.reuseTls,'boolean');});
  const holdout=await scenario(sources,choice.selected,99,{prefix:248});test('holdout passes segment rollover',()=>assert.equal(holdout.rows,136));
  const crash=await scenario(sources,{window:4,batch:8,reuseTls:true},100,{crash:true,prefix:256});test('crash resumed without duplicate committed rows',()=>assert.equal(crash.rows,128));
  const avg=(x)=>x.reduce((a,b)=>a+b,0)/x.length;const effects={};for(const [name,a,b] of [['window',1,4],['batch',4,8],['reuseTls',false,true]]){const low=results.filter(x=>x[name]===a).map(x=>x.recordsPerSecond);const high=results.filter(x=>x[name]===b).map(x=>x.recordsPerSecond);effects[name]={from:a,to:b,lowMean:+avg(low).toFixed(2),highMean:+avg(high).toFixed(2),difference:+(avg(high)-avg(low)).toFixed(2)};}
  const report={sheet:164,status:'PASS',checks,seed:'0x164bad5',design:'2 x 2 x 2 factorial randomized within each of two blocks; per-page deterministic 3..14ms injected tail latency',factors:{window:[1,4],batch:[4,8],tlsReuse:[false,true]},sourceRecords:sourceHead.count,benchmarkRowsRecovered:128,results,effects,policySelection:choice,holdout,crash,host:os.hostname(),node:process.version,cpu:os.cpus()[0].model,warning:'One physical host, only two replicates per configuration; policy selected on test data and evaluated on one holdout. Timings are observational, not a generalizable guarantee.'};fs.writeFileSync(path.join(__dirname,'benchmark164.json'),JSON.stringify(report,null,2)+'\n');console.log('SHEET164 GATE '+checks+'/'+checks+' PASS');
 }finally{await Promise.allSettled(Object.values(sources).map(stop));}}
main().catch(e=>{console.error('SHEET164 FAIL',e.stack||e);process.exitCode=1;}).finally(async()=>{await Promise.allSettled(processes.map(stop));if(process.env.S164_KEEP!=='1')fs.rmSync(root,{recursive:true,force:true});});
