from pathlib import Path
import json,html
B=Path(__file__).resolve().parent
j=json.loads((B/'benchmark164.json').read_text())
rows=[]
for score in j['policySelection']['scored']:
 w,b,t=score['key'].split('/')
 trial=[x for x in j['results'] if x['window']==int(w) and x['batch']==int(b) and x['reuseTls']==(t=='true')]
 rows.append(dict(key=score['key'],window=int(w),batch=int(b),reuseTls=t=='true',median=score['medianRowsPerSecond'],trials=trial))
js=json.dumps({'rows':rows,'effects':j['effects'],'selected':j['policySelection']['selected'],'holdout':j['holdout'],'crash':j['crash']},separators=(',',':'))
page=r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OASIS • SHEET 164 Factorial Benchmark</title><style>
:root{color-scheme:dark;--bg:#05100d;--card:#10251e;--line:#295440;--ink:#e9fff4;--dim:#9fbcaf;--accent:#4ef7a5;--accent2:#b6ffa4}*{box-sizing:border-box}body{margin:0;background:radial-gradient(ellipse at 25% 0,#143b2a,#05100d 54%);color:var(--ink);font:15px/1.55 ui-monospace,Consolas,Menlo,monospace;min-height:100vh}main{max-width:1210px;padding:42px 26px 70px;margin:auto}a{color:var(--accent)}h1{font-size:clamp(2rem,5vw,4.2rem);line-height:1.06;letter-spacing:-.05em;margin:14px 0 6px}h2{font-size:1.15rem;margin:0 0 17px}p{color:var(--dim);max-width:76ch}.over{font-size:.78rem;letter-spacing:.23em;color:var(--accent);text-transform:uppercase}.meta{margin:5px 0 28px}.cols{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:22px 0 28px}.stats,.panel{background:linear-gradient(145deg,rgba(22,57,43,.8),rgba(10,29,23,.88));border:1px solid var(--line);border-radius:16px;padding:21px}.num{font-size:clamp(1.45rem,3.1vw,2.6rem);font-weight:700;color:var(--accent);line-height:1.3}.hint{font-size:.83rem;color:var(--dim)}.layout{display:grid;grid-template-columns:minmax(0,1.3fr) minmax(320px,.7fr);gap:17px}.bar{display:grid;grid-template-columns:112px 1fr 84px;align-items:center;gap:12px;margin:12px 0}.track{height:18px;border:1px solid #366b4d;background:#061c13;border-radius:7px;overflow:hidden}.fill{height:100%;background:linear-gradient(90deg,#277f55,#4ef7a5);border-radius:6px;min-width:2px}.bar.active .fill{background:linear-gradient(90deg,#73b74c,#ccff9e)}.bar .tag{background:none;border:0;color:var(--ink);font:inherit;cursor:pointer;text-align:left;padding:8px 0}.bar .tag:hover,.bar.active .tag{color:var(--accent2)}.value{text-align:right;font-variant-numeric:tabular-nums;font-size:.84rem}.item{width:100%;padding:12px;background:transparent;border:1px solid var(--line);border-radius:8px;color:var(--ink);font:inherit;cursor:pointer;text-align:left;margin:4px 0}.item:hover,.item[aria-pressed=true]{border-color:var(--accent);background:rgba(78,247,165,.09)}.scenario{font-size:.75rem;color:var(--dim)}svg{width:100%;height:auto}.flow{white-space:pre;overflow:auto;background:#06140f;padding:12px;border:1px solid var(--line);border-radius:10px;color:#b3fdd1;font-size:.8rem}.btn{background:var(--accent);color:#062018;font:700 14px ui-monospace,monospace;border:0;border-radius:10px;padding:12px 16px;cursor:pointer}.btn:hover{background:#acffc7}.footer{font-size:.8rem;color:var(--dim);margin-top:21px}.status{display:inline-block;border:1px solid #4bbf81;background:#0d3221;color:#aaffca;border-radius:100px;font-size:.75rem;padding:4px 11px;margin-top:12px}#detail{min-height:180px}#detail pre{white-space:pre-wrap;overflow-wrap:anywhere;color:var(--accent2)}@media(max-width:840px){.layout{grid-template-columns:1fr}.cols{grid-template-columns:1fr}.bar{grid-template-columns:100px 1fr 72px}main{padding:25px 15px}}
</style></head><body><main><div class="over">ROOT0 // OASIS // performance verification</div><h1>SHEET <span style="color:var(--accent)">164</span><br>RECOVERY FACTORIAL</h1><p class="meta">2×2×2 randomized benchmark · Merkle-verified ordered writes · live mTLS · 2026-10-09</p><span class="status">0e PASS · 68 / 68 new checks</span>
<div class="cols"><div class="stats"><div class="num">8 × 2</div><div class="hint">factorial variants × blocks</div></div><div class="stats"><div class="num">45 / 45</div><div class="hint">inherited S163 isolated checks</div></div><div class="stats"><div class="num">4 / 8 / TLS</div><div class="hint">tuning dimensions</div></div></div>
<div class="layout"><section class="panel"><h2>Measured median recovery throughput</h2><p>Rows/second. Select a bar to inspect both trial measurements, request counts and TLS handshakes.</p><div id="bars" role="group" aria-label="Benchmark configurations"></div><p class="hint">Within each trial, only the selected performance switches differ. Two replicates are not enough for confidence intervals.</p></section>
<section class="panel"><h2>Authenticated scenario inspector</h2><div id="detail" aria-live="polite"></div><div id="special"><button type="button" class="item" id="holdout">↗ HOLDOUT · segment rollover</button><button type="button" class="item" id="crash">↗ CRASH · persisted write, lost ACK</button><button type="button" class="item" id="effects">↗ MARGINAL EFFECTS · factor means</button></div><button type="button" class="btn" id="export">Export benchmark JSON</button><p class="scenario" id="export-status">No export generated</p></section></div>
<div class="panel" style="margin-top:17px"><h2>Signed and ordered recovery pipeline</h2><svg viewBox="0 0 920 144" aria-label="Quorum to Merkle verification to parallel fetch to ordered batches and crash recovery" role="img"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0 0 L7 3 L0 6" fill="none" stroke="#71dfaa" stroke-width="1.4"/></marker></defs><g stroke="#347f61" stroke-width="1.5" fill="#102e22"><rect x="4" y="27" width="145" height="84" rx="12"/><rect x="184" y="27" width="145" height="84" rx="12"/><rect x="364" y="27" width="145" height="84" rx="12"/><rect x="544" y="27" width="158" height="84" rx="12"/><rect x="738" y="27" width="178" height="84" rx="12"/></g><g stroke="#71dfaa" stroke-width="2" marker-end="url(#arrow)"><path d="M149 69 H180"/><path d="M329 69 H360"/><path d="M509 69 H540"/><path d="M702 69 H734"/></g><g fill="#d2ffea" font-family="monospace" text-anchor="middle" font-size="13"><text x="77" y="61">SIGNED 2/3</text><text x="77" y="79">QUORUM</text><text x="256" y="61">MERKLE</text><text x="256" y="79">VERIFY</text><text x="436" y="61">PARALLEL</text><text x="436" y="79">PREFETCH</text><text x="622" y="61">ORDERED FSYNC</text><text x="622" y="79">BATCH 4 / 8</text><text x="827" y="61">RESTART-SAFE</text><text x="827" y="79">CURSOR</text></g></svg><p class="footer">TLS certificate pinning stays enforced for both reused and fresh sockets. Speculative fetching never authorizes speculative writes.</p></div><p class="footer">Single-host laboratory benchmark. Results do not establish cross-host atomicity or universal throughput. Source: benchmark164.json · SHA-256 authenticated archive.</p></main><script>
const data=__DATA__;
const root=document.getElementById('bars'),detail=document.getElementById('detail');
const formatted=x=>Number(x).toFixed(2),cls=k=>k.replaceAll('/','-');
function inspect(row){document.querySelectorAll('.bar').forEach(el=>el.classList.toggle('active',el.dataset.key===row.key));detail.innerHTML='<div class="over">FACTORS</div><h2>'+row.window+' prefetch / '+row.batch+' records / TLS '+(row.reuseTls?'reused':'fresh')+'</h2><div class="num">'+formatted(row.median)+' /s</div><div class="hint">Median of two throughput observations</div><pre>'+row.trials.map(x=>'block '+(x.block+1)+': '+formatted(x.recordsPerSecond)+' /s  · TLS '+x.tlsConnections+'/'+x.requests+' · '+formatted(x.seconds)+' sec').join('\n')+'</pre>';}
const max=Math.max(...data.rows.map(x=>x.median));for(const row of data.rows){const e=document.createElement('div');e.className='bar';e.dataset.key=row.key;e.innerHTML='<button class="tag" aria-label="Inspect '+row.key+'" type="button">'+row.window+'x / '+row.batch+' / '+(row.reuseTls?'KA':'NEW')+'</button><div class="track"><div class="fill" style="width:'+(100*row.median/max).toFixed(1)+'%"></div></div><div class="value">'+formatted(row.median)+'</div>';e.querySelector('button').onclick=()=>inspect(row);root.appendChild(e);}
function view(kind){document.querySelectorAll('.bar').forEach(e=>e.classList.remove('active'));if(kind==='holdout'){const d=data.holdout;detail.innerHTML='<div class="over">EXTERNAL HOLDOUT</div><h2>Trusted segment rollover</h2><div class="num">'+formatted(d.recordsPerSecond)+'/s</div><pre>records: '+d.rows+'\nstart: '+d.prefix+'\nend: '+(d.prefix+d.rows)+'\nverified Merkle root: PASS</pre>';}else if(kind==='crash'){detail.innerHTML='<div class="over">FAULT INJECTION</div><h2>Real resource-process kill</h2><div class="num">NO DUPLICATES</div><pre>durable batch before ACK\nSIGEXIT -> process restart\nauthenticated cursor -> continue\nfinal Merkle root: PASS</pre>';}else{detail.innerHTML='<div class="over">AVERAGE MARGINAL EFFECTS</div><h2>Descriptive factor comparison</h2><pre>'+Object.entries(data.effects).map(([k,v])=>k+'\n  low '+formatted(v.lowMean)+'/s\n  high '+formatted(v.highMean)+'/s\n  change '+formatted(v.difference)+'/s').join('\n')+'</pre>';}}
for(const key of ['holdout','crash','effects'])document.getElementById(key).onclick=()=>view(key);
document.getElementById('export').onclick=()=>{const bytes=JSON.stringify(data,null,2);const blob=new Blob([bytes],{type:'application/json'}),url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='SHEET164-benchmark-export.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),250);document.getElementById('export-status').textContent='Export prepared · '+bytes.length+' characters';};
inspect(data.rows[0]);
</script></body></html>'''
(B/'index.html').write_text(page.replace('__DATA__',js))
print('wrote html',len(page))
