#!/usr/bin/env python3
"""SHEET 48: append-only 17-era blink-to-open-tunnel provenance audit."""
import hashlib,importlib.util,json,math
from pathlib import Path
P=Path(__file__).resolve().parent
sp=importlib.util.spec_from_file_location("sheet45",P.parent/"sheet-45"/"sheet45-exitron-v01.py")
base=importlib.util.module_from_spec(sp);sp.loader.exec_module(base)
LAYERS=((1832,"TELEGRAPH_IDEA"),(1844,"TELEGRAPH_MESSAGE"),(1866,"TRANSATLANTIC_CABLE"),(1876,"TELEPHONE"),(1901,"TRANSATLANTIC_WIRELESS"),(1945,"MEMEX"),(1969,"ARPANET"),(1973,"INTERNATIONAL_ARPANET"),(1983,"TCP_IP"),(1991,"WWW"),(1995,"WEB_COMMERCIAL"),(2001,"CORPUS"),(2006,"CLOUD"),(2011,"MOBILE"),(2016,"RANK"),(2019,"PRELOAD"),(2024,"GENERATE"))
PERIOD=360;MULTIPLICITY=3
def digest(x):return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def open_at(t):return math.sin(2*math.pi*(t%PERIOD)/PERIOD)>.2
def benchmark():
 state=base.START;tip="0"*64;records=[];stats=[];seen={state}
 for i,(year,word) in enumerate(LAYERS):
  emitted=held=eligible=opened=0
  dest=LAYERS[i+1][1] if i+1<len(LAYERS) else "EXTERIOR_SINK"
  previous=tip
  for sector in range(PERIOD):
   tick=i*PERIOD+sector;gate=open_at(tick);opened+=int(gate)
   state,events=base.travel(state,tick);seen.add(state)
   for _,node,pair,half,original_gate in events:
    eligible+=MULTIPLICITY
    if not gate:held+=MULTIPLICITY;continue
    for particle in range(MULTIPLICITY):
     event=dict(tick=tick,layer=i+1,year=year,word=word,destination=dest,
         node=node,pair=pair,half=half,particle=particle,channel="<................>")
     h=digest(dict(prev=tip,event=event))
     records.append(dict(prev=tip,event=event,sha=h));tip=h;emitted+=1
  stats.append(dict(year=year,word=word,destination=dest,open_ticks=opened,
     opportunities=eligible,emitted=emitted,held=held,initial_tip=previous,final_tip=tip))
 end_hash=digest(state)
 for tick in range(len(LAYERS)*PERIOD-1,-1,-1):state,_=base.travel(state,tick,True)
 chain=all(r["prev"]==(records[j-1]["sha"] if j else "0"*64) and
       r["sha"]==digest(dict(prev=r["prev"],event=r["event"])) for j,r in enumerate(records))
 forged=dict(records[0]["event"]);forged["word"]="FORGED"
 tamper=digest(dict(prev=records[0]["prev"],event=forged))!=records[0]["sha"]
 checks=dict(
   seventeen_layers=len(stats)==17,first_year_1832=stats[0]["year"]==1832,
   years_strictly_increasing=all(stats[i]["year"]<stats[i+1]["year"] for i in range(16)),
   sectors_6120=len(LAYERS)*PERIOD==6120,
   updates_122400=len(LAYERS)*PERIOD*20==122400,
   wall_blinks_each_layer=all(0<s["open_ticks"]<PERIOD for s in stats),
   token_conservation=all(s["emitted"]+s["held"]==s["opportunities"] for s in stats),
   flood_only_open=all(open_at(r["event"]["tick"]) for r in records),
   handoff_destinations=all(stats[i]["destination"]==stats[i+1]["word"] for i in range(16)),
   all_emissions_recorded=sum(s["emitted"] for s in stats)==len(records),
   provenance_hash_chain=chain,tamper_detected=tamper,
   exact_reverse=state==base.START,
   distinct_tick_boundaries=len(seen)==len(LAYERS)*PERIOD+1)
 result=dict(schema="oasis/sheet48/handoff-v01",ticks=6120,node_updates=122400,
    layers=stats,total_opportunities=sum(s["opportunities"] for s in stats),
    emitted_tokens=len(records),held_tokens=sum(s["held"] for s in stats),
    open_ticks=sum(s["open_ticks"] for s in stats),
    distinct_tick_states=len(seen),final_hash=end_hash,ledger_tip=tip,
    reversed_exact=state==base.START,checks=checks,passed=sum(checks.values()),total=len(checks),
    limitations=["Timeline labels are assigned, not generated by the model",
    "Provenance is a sidecar ledger, not an embedded watermark",
    "No actual quantum tunneling or real network handoff is asserted"])
 return result
if __name__=="__main__":
 r=benchmark();print(json.dumps(r,indent=2));assert r["passed"]==r["total"]
